"""triggerctl — triggers for Claude Code.

Two-tier design:
- cheap detection tier (pure Python): evaluate schedule + probe, dedup via run-log.
- model execution tier: only invoke `claude -p` for triggers that are actually DUE.

Source of truth = each trigger's own .md (YAML frontmatter + body).
TRIGGERS.md (the flat index) is generated by `triggerctl sync`.
"""

__version__ = "0.1.0"
