"""Health checks for triggerctl installation and embedding."""
from __future__ import annotations

import json
import os
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional

from . import registry
from . import hermes as hermes_mod
from .model import discover
from .roots import Root, all_roots, project_root, user_root
from .hookgen import TOO_MANY_THRESHOLD
from .tz import tz_label, tz_offset


@dataclass
class Check:
    name: str
    status: str   # ok | warn | fail | info
    detail: str


@dataclass
class Report:
    checks: List[Check] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not any(c.status == "fail" for c in self.checks)

    def add(self, name: str, status: str, detail: str) -> None:
        self.checks.append(Check(name, status, detail))


def _index_stale(root: Root) -> bool:
    idx = root.index_file
    if not idx.exists():
        return True
    idx_mtime = idx.stat().st_mtime
    for t in discover(root):
        if t.path.stat().st_mtime > idx_mtime:
            return True
    marker = "<!-- AUTO-GENERATED by `triggerctl sync`"
    if marker not in idx.read_text(encoding="utf-8"):
        return True
    return False


def _settings() -> dict:
    p = Path.home() / ".claude" / "settings.json"
    if not p.exists():
        return {}
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _poll_running(root: Root) -> bool:
    script = root.path / "run-loop.sh"
    if not script.exists():
        return False
    try:
        cp = subprocess.run(
            ["pgrep", "-f", str(script)],
            capture_output=True,
            text=True,
            check=False,
        )
        return cp.returncode == 0 and bool(cp.stdout.strip())
    except Exception:
        return False


def run(start: Optional[Path] = None) -> Report:
    rep = Report()

    tctl = shutil.which("triggerctl")
    if tctl:
        rep.add("triggerctl binary", "ok", tctl)
    else:
        rep.add(
            "triggerctl binary",
            "fail",
            "not on PATH → bash install.sh or /opt/conda/bin/python3 -m pip install -e .",
        )

    ur = user_root()
    if ur.path.is_dir():
        rep.add("user triggers root", "ok", str(ur.path))
    else:
        rep.add("user triggers root", "warn", "missing → triggerctl init --root user")

    skill = Path.home() / ".claude" / "skills" / "triggerctl" / "SKILL.md"
    if skill.exists():
        rep.add("triggerctl skill", "ok", str(skill))
    else:
        rep.add(
            "triggerctl skill",
            "warn",
            "missing ~/.claude/skills/triggerctl/SKILL.md (install.sh installs it)",
        )

    data = _settings()
    hook_ok = False
    for group in data.get("hooks", {}).get("UserPromptSubmit", []):
        for h in group.get("hooks", []):
            if "triggerctl hook" in h.get("command", ""):
                hook_ok = True
                break
    if hook_ok:
        rep.add("Claude UserPromptSubmit hook", "ok", "semantic session triggers configured")
    else:
        rep.add(
            "Claude UserPromptSubmit hook",
            "warn",
            "not configured → triggerctl install --hook",
        )

    try:
        _, hcfg = hermes_mod.load_config()
        if hermes_mod.hook_installed(hcfg):
            rep.add("Hermes pre_llm_call hook", "ok", f"configured in {hermes_mod.config_path()}")
        elif shutil.which("hermes"):
            rep.add(
                "Hermes pre_llm_call hook",
                "warn",
                "Hermes found but hook missing → triggerctl install --hermes",
            )
        else:
            rep.add(
                "Hermes pre_llm_call hook",
                "info",
                "optional → triggerctl install --hermes (Hermes Agent)",
            )
    except Exception as exc:  # noqa: BLE001
        rep.add("Hermes pre_llm_call hook", "warn", f"could not read Hermes config: {exc}")

    if shutil.which("hermes"):
        if hermes_mod.skill_installed():
            rep.add("Hermes triggerctl skill", "ok", str(hermes_mod.skill_path()))
        else:
            rep.add(
                "Hermes triggerctl skill",
                "info",
                "optional → triggerctl install --hermes",
            )

    env = data.get("env") or {}
    if str(env.get("TRIGGERCTL_HOOK_REPLACE", "")).lower() in ("1", "true", "yes"):
        rep.add("hook replace mode", "ok", "TRIGGERCTL_HOOK_REPLACE enabled (experimental)")
    else:
        rep.add(
            "hook replace mode",
            "info",
            "set TRIGGERCTL_HOOK_REPLACE=1 in settings env for latest-only injection",
        )

    sl = data.get("statusLine", {})
    if isinstance(sl, dict) and "triggerctl statusline" in sl.get("command", ""):
        rep.add("statusLine", "ok", sl.get("command", ""))
    else:
        rep.add(
            "statusLine",
            "info",
            "optional → triggerctl install --statusline",
        )

    cm = ur.claude_md
    if cm.exists() and registry.CLAUDE_START in cm.read_text(encoding="utf-8"):
        rep.add(
            "user CLAUDE.md session block",
            "warn",
            "legacy block present → triggerctl sync --root user",
        )
    elif ur.path.is_dir() and any(t.in_context for t in discover(ur)):
        rep.add(
            "user CLAUDE.md session block",
            "info",
            "session via hook; no CLAUDE block needed",
        )

    pr = project_root(start)
    if pr.path.is_dir() and discover(pr):
        pcm = pr.claude_md
        if pcm.exists() and registry.CLAUDE_START in pcm.read_text(encoding="utf-8"):
            rep.add(
                "project CLAUDE.md session block",
                "warn",
                "legacy block present → triggerctl sync --root project",
            )

    for root in all_roots(start):
        if not root.path.is_dir():
            continue
        label = "user" if root.kind == "user" else "project"
        if _index_stale(root):
            rep.add(
                f"{label} index",
                "warn",
                f"{root.index_file} stale or missing → triggerctl sync --root {root.kind}",
            )
        else:
            rep.add(f"{label} index", "ok", str(root.index_file))

        enabled = [t for t in discover(root) if t.enabled]
        poll_types = [t for t in enabled if t.kind in ("time", "event", "time+event")]
        if poll_types:
            if _poll_running(root):
                rep.add(f"{label} poll loop", "ok", "run-loop.sh running")
            else:
                rep.add(
                    f"{label} poll loop",
                    "warn",
                    f"{len(poll_types)} time/event trigger(s) but no poll loop → triggerctl install --loop",
                )

        if len(enabled) > TOO_MANY_THRESHOLD:
            rep.add(
                f"{label} trigger count",
                "warn",
                f"{len(enabled)} enabled (>{TOO_MANY_THRESHOLD}) — also shown in statusLine → triggerctl disable <name>",
            )

    tz = os.environ.get("TRIGGERCTL_TZ_OFFSET")
    if tz is not None and tz != "":
        rep.add(
            "timezone offset",
            "ok",
            f"TRIGGERCTL_TZ_OFFSET={tz} (schedule/poll use {tz_label()})",
        )
    else:
        rep.add(
            "timezone offset",
            "info",
            f"TRIGGERCTL_TZ_OFFSET unset, default +8 ({tz_label()})",
        )

    if shutil.which("git"):
        rep.add("git", "ok", shutil.which("git") or "")
    else:
        rep.add("git", "warn", "git not installed; triggerctl add --from remote unavailable")

    return rep


def format_report(rep: Report) -> str:
    icons = {"ok": "✓", "warn": "!", "fail": "✗", "info": "·"}
    lines = ["triggerctl doctor", ""]
    for c in rep.checks:
        icon = icons.get(c.status, "?")
        lines.append(f"  [{icon}] {c.name}: {c.detail}")
    lines.append("")
    if rep.ok:
        suffix = " (warnings present)" if any(x.status == "warn" for x in rep.checks) else ""
        lines.append(f"summary: no fatal issues{suffix}")
    else:
        lines.append("summary: fix items marked ✗")
    return "\n".join(lines)
