"""Generate TRIGGERS.md and manage CLAUDE.md (strict context policy).

Policy:
- TRIGGERS.md is an **ops index only** — not injected into agent context.
- Lists enabled semantic session triggers with inject!=false.
- time / event / time+event triggers never appear (poll reads files directly).
- CLAUDE.md managed session block is not written — hook is the injection point.
"""
from __future__ import annotations

from typing import List

from .model import Trigger, discover
from .roots import Root

_MARK = "<!-- AUTO-GENERATED by `triggerctl sync` — do not edit -->"


def _session_for_context(triggers: List[Trigger]) -> List[Trigger]:
    return [t for t in triggers if t.in_context]


def render(root: Root, triggers: List[Trigger]) -> str:
    scope = "user" if root.kind == "user" else "project"
    sess = _session_for_context(triggers)
    lines = [
        f"# TRIGGERS ({scope} · semantic session · ops index)",
        "",
        _MARK,
        "",
        "> **Not injected into agent context.** Semantic session triggers are injected via the",
        "> UserPromptSubmit hook each turn. time/event triggers run via `triggerctl poll` only.",
        "> Full list: `triggerctl list --root " + root.kind + "`.",
        "",
        "| name | when | file |",
        "|---|---|---|",
    ]
    if not sess:
        lines.append("| _(none)_ | | |")
    for t in sorted(sess, key=lambda x: x.name):
        when = (t.when or "").replace("|", "\\|")
        lines.append(f"| {t.name} | {when} | {t.rel_path} |")
    lines.append("")
    return "\n".join(lines)


CLAUDE_START = "<!-- triggerctl:session-triggers:start (auto-generated, do not edit) -->"
CLAUDE_END = "<!-- triggerctl:session-triggers:end -->"


def strip_claude_session_block(root: Root) -> bool:
    """Remove legacy managed block from CLAUDE.md (context now via hook only)."""
    path = root.claude_md
    if not path.exists():
        return False
    text = path.read_text(encoding="utf-8")
    if "triggerctl:session-triggers:start" not in text or CLAUDE_END not in text:
        return False
    start_marker = text.index("triggerctl:session-triggers:start")
    block_start = text.rfind("<!--", 0, start_marker)
    end_idx = text.index(CLAUDE_END) + len(CLAUDE_END)
    pre = text[:block_start].rstrip("\n")
    post = text[end_idx:].lstrip("\n")
    new = (pre + ("\n\n" + post if post else "\n")).rstrip("\n") + "\n"
    path.write_text(new, encoding="utf-8")
    return True


def sync(root: Root) -> int:
    """Regenerate TRIGGERS.md (ops index) and strip CLAUDE.md managed block."""
    triggers = discover(root)
    root.path.mkdir(parents=True, exist_ok=True)
    root.index_file.write_text(render(root, triggers), encoding="utf-8")
    strip_claude_session_block(root)
    return len(triggers)
