"""Generate the flat TRIGGERS.md index from scanning trigger files.

TRIGGERS.md is a generated artifact (the single authoritative, one-level index the
model reads on every request). Source of truth stays in each trigger's frontmatter.
"""
from __future__ import annotations

from typing import List

from .model import Trigger, discover
from .roots import Root

_MARK = "<!-- AUTO-GENERATED by `triggerctl sync` — 不要手改，改触发器文件后重跑 sync -->"


def render(root: Root, triggers: List[Trigger]) -> str:
    scope = "用户级 / 全局" if root.kind == "user" else "项目级"
    lines = [
        f"# TRIGGERS（{scope}）",
        "",
        _MARK,
        "",
        "触发器机制：满足条件时自动执行登记的命令/prompt。和 `skills` 平级，支持多注册根。",
        "",
        "> **唯一权威索引（一级）**：所有触发器及条件都在下表。源真相在各触发器文件的 frontmatter；",
        "> 本文件由 `triggerctl sync` 生成。引擎见 [triggerctl](https://github.com/) / `python -m triggerctl`。",
        "",
        "## 注册表（仅启用的；停用的不在此、也不占用上下文）",
        "",
        "| 名称 | 类型 | 触发条件 | 文件 |",
        "|---|---|---|---|",
    ]
    enabled = [t for t in triggers if t.enabled]
    disabled = [t for t in triggers if not t.enabled]
    if not enabled:
        lines.append("| _(无启用的触发器)_ | | | |")
    for t in sorted(enabled, key=lambda x: x.name):
        cond = t.condition_summary().replace("|", "\\|")
        lines.append(f"| {t.name} | {t.kind} | {cond} | {t.rel_path} |")
    if disabled:
        lines += [
            "",
            f"> 另有 **{len(disabled)} 个已停用**触发器（故意不列出以节省上下文）。"
            f"管理：`triggerctl list`（含停用）/ `triggerctl enable <名称>` 开启。",
        ]

    lines += [
        "",
        "## 类型（由 frontmatter 字段推断）",
        "",
        "| 类型 | 声明 | 触发判定 | 谁评估 |",
        "|---|---|---|---|",
        "| `time` | 只有 `schedule` | 到点（now ≥ 当前周期目标时刻） | 轮询(便宜检测层) |",
        "| `event` | 只有 `probe` | `probe` 退出码 0（条件成立） | 轮询(便宜检测层) |",
        "| `time+event` | `schedule` + `probe` | 都满足才触发（AND） | 轮询 |",
        "| `session` | 有 `when` | 由你（Agent）在会话内按 `when` 自行判断 | **会话内自查** |",
        "",
        "> `session` 型（`when`）是**语义条件**，没有 shell 探针能判定，轮询器跳过它。",
        "> 你在开发/处理请求过程中，对照下表 `session` 型的条件自检，满足就执行其正文动作。",
        "",
        "## 执行约定（重要）",
        "",
        "**凡因触发器而执行动作或发提醒，必须在消息开头注明来源**，格式 `[触发器: <名称>] …`，",
        "让用户清楚这是触发器驱动的、而非你自发的。例如：`[触发器: auto-commit-push] 已完成一个特性，自动提交。`",
        "",
        "## 轮询（两层）",
        "",
        "- 检测层（便宜，纯 Python，无模型）：`python -m triggerctl detect`",
        "- 轮询（检测 + 仅对 DUE 调模型执行）：`python -m triggerctl poll`",
        "- 高频拉起：`python -m triggerctl install --loop --interval 60` 后台跑；或 cron：`triggerctl install --cron`",
        "- 去重状态：`.state/run-log.jsonl`",
        "",
    ]
    return "\n".join(lines)


def sync(root: Root) -> int:
    """Regenerate TRIGGERS.md for a root. Returns number of triggers indexed."""
    triggers = discover(root)
    root.path.mkdir(parents=True, exist_ok=True)
    root.index_file.write_text(render(root, triggers), encoding="utf-8")
    return len(triggers)
