"""Validate trigger files, names, schedules, and index freshness."""
from __future__ import annotations

import subprocess
from collections import defaultdict
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

from . import schedule as sched
from .model import discover
from .roots import Root, resolve
from .tz import effective_now

PROBE_TIMEOUT = 10
INDEX_MARKER = "<!-- AUTO-GENERATED by `triggerctl sync`"


@dataclass
class Issue:
    level: str   # error | warn
    root: str
    name: str
    message: str


@dataclass
class Report:
    issues: List[Issue] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not any(i.level == "error" for i in self.issues)

    def add(self, level: str, root: str, name: str, message: str) -> None:
        self.issues.append(Issue(level, root, name, message))


def _index_stale(root: Root) -> bool:
    idx = root.index_file
    if not idx.exists():
        return True
    if INDEX_MARKER not in idx.read_text(encoding="utf-8"):
        return True
    idx_mtime = idx.stat().st_mtime
    return any(t.path.stat().st_mtime > idx_mtime for t in discover(root))


def _run_probe(cmd: str) -> Tuple[int, str]:
    try:
        p = subprocess.run(
            cmd, shell=True, capture_output=True, text=True, timeout=PROBE_TIMEOUT
        )
        return p.returncode, (p.stderr or p.stdout or "").strip()[:120]
    except subprocess.TimeoutExpired:
        return 124, "timeout"
    except Exception as e:  # noqa: BLE001
        return 1, str(e)


def _body_is_stub(body: str) -> bool:
    text = body.strip()
    return not text or "TODO" in text and len(text) < 200


def validate_roots(
    roots: List[Root],
    probe_test: bool = False,
) -> Report:
    rep = Report()
    names: Dict[str, List[Tuple[str, str]]] = defaultdict(list)

    for root in roots:
        if not root.path.is_dir():
            rep.add("warn", str(root), "-", "注册根目录不存在")
            continue

        if _index_stale(root):
            rep.add(
                "warn",
                str(root),
                "(index)",
                f"TRIGGERS.md 过期或缺失 → triggerctl sync --root {root.kind}",
            )

        for t in discover(root):
            names[t.name].append((str(root), t.rel_path))

            if t.path.stem != t.name:
                rep.add("warn", str(root), t.name, f"文件名 {t.path.name} 与 name 不一致")

            if t.kind == "invalid":
                rep.add("error", str(root), t.name, "缺少 schedule/probe/when，类型无效")
                continue

            if t.schedule:
                try:
                    sched.target_and_key(t.schedule, t.dedup, effective_now())
                except Exception as e:  # noqa: BLE001
                    rep.add("error", str(root), t.name, f"schedule 无效: {e}")

            if probe_test and t.probe:
                rc, detail = _run_probe(t.probe)
                if rc != 0:
                    rep.add(
                        "warn",
                        str(root),
                        t.name,
                        f"probe 试跑未通过(rc={rc})" + (f": {detail}" if detail else ""),
                    )
                if t.dedup_cmd:
                    rc, detail = _run_probe(t.dedup_cmd)
                    if rc != 0:
                        rep.add(
                            "warn",
                            str(root),
                            t.name,
                            f"dedup_cmd 试跑失败(rc={rc})" + (f": {detail}" if detail else ""),
                        )

            if _body_is_stub(t.body):
                rep.add("warn", str(root), t.name, "正文仍是 TODO 占位，触发时模型不知道做什么")

    for name, locs in names.items():
        if len(locs) > 1:
            where = ", ".join(f"{r}:{p}" for r, p in locs)
            rep.add("error", "all", name, f"名称重复: {where}")

    return rep


def validate(selector: Optional[str] = None, probe_test: bool = False) -> Report:
    return validate_roots(resolve(selector), probe_test=probe_test)


def format_report(rep: Report) -> str:
    if not rep.issues:
        return "validate: 全部通过"
    icons = {"error": "✗", "warn": "!"}
    lines = ["validate", ""]
    for i in rep.issues:
        icon = icons.get(i.level, "?")
        label = i.name if i.name != "-" else ""
        prefix = f"  [{icon}] {label}: " if label else f"  [{icon}] "
        lines.append(f"{prefix}{i.message}  ({i.root})")
    errs = sum(1 for x in rep.issues if x.level == "error")
    warns = sum(1 for x in rep.issues if x.level == "warn")
    lines.append("")
    lines.append(f"汇总: {errs} 错误, {warns} 警告")
    return "\n".join(lines)
